name: FallbackExample
description: Composite with fallback

inputs:
  param1:
    description: "First param"
    default: "default1"
  param2:
    description: "Second param"
    default: "default2"
  param3:
    description: "Third param"
    default: "default3"

runs:
  using: composite
  steps:
    - name: Set env vars with fallback
      shell: bash
      run: |
        PARAM1="${{ inputs.param1 }}"
        PARAM2="${{ inputs.param2 }}"
        PARAM3="${{ inputs.param3 }}"
        DEFAULT_PARAM1="default1"
        DEFAULT_PARAM2="default2"
        DEFAULT_PARAM3="default3"

        if [ -z "$PARAM1" ]; then PARAM1="$DEFAULT_PARAM1"; fi
        if [ -z "$PARAM2" ]; then PARAM2="$DEFAULT_PARAM2"; fi
        if [ -z "$PARAM3" ]; then PARAM3="$DEFAULT_PARAM3"; fi

        echo "param1=$PARAM1" >> "$GITHUB_ENV"
        echo "param2=$PARAM2" >> "$GITHUB_ENV"
        echo "param3=$PARAM3" >> "$GITHUB_ENV"

    - name: Use param1
      run: echo "$param1"
      shell: bash

    - name: Use param2
      run: echo "$param2"
      shell: bash

    - name: Use param3
      run: echo "$param3"
      shell: bash
