name: Read file
description: |
  リポジトリ内の別ファイルを読み込んでアクションで利用する
  AI向けのプロンプトをmarkdownで記述している場合などを想定

on:
  workflow_dispatch:
  push:
    branches:
      - chore/read-file-action

jobs:
  read-file:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read prompt
        id: prompt
        uses: juliangruber/read-file-action@v1
        with:
          path: ./docs/ai-review-prompt.md

      - name: Echo prompt
        run: echo "${{ steps.prompt.outputs.content }}"
