name: SFTP Deploy

on:
  push:
    branches:
      - feature/sftp-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH Key
        env:
          SFTP_KEY: ${{ secrets.SFTP_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SFTP_KEY" > ~/.ssh/sftp_key
          chmod 600 ~/.ssh/sftp_key

      - name: Upload files via SFTP
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_REMOTE_PATH: ${{ vars.SFTP_REMOTE_PATH }}
        run: |
          sftp -o StrictHostKeyChecking=no -i ~/.ssh/sftp_key -P 2922 $SFTP_USERNAME@$SFTP_SERVER <<EOF
          cd $SFTP_REMOTE_PATH
          put -r ./dist/*
          bye
          EOF
